INSERT INTO stoves (name_it, slug, active, sort_order, categoria, potenza, dimensioni, peso) VALUES
('Margherita',         'margherita',          true, 1080, 'Stufa a Legna',              '12,0 kW',          NULL, NULL),
('Brando',             'brando',              true, 1090, 'Stufa a Legna',              '14,5 kW',          NULL, NULL),
('Ginevra',            'ginevra',             true, 1100, 'Stufa a Legna',              '9,5 kW',           NULL, NULL),
('Alberta',            'alberta',             true, 1110, 'Stufa a Legna',              '9,5 kW',           NULL, NULL),
('Patty',              'patty',               true, 1120, 'Stufa a Legna',              '9,5 kW',           NULL, NULL),
('Marica',             'marica',              true, 1130, 'Stufa a Legna',              '9,5 kW',           NULL, NULL),
('Livia',              'livia',               true, 1140, 'Stufa a Legna',              '9,5 kW',           NULL, NULL),
('Livia Ventilata',    'livia-ventilata',     true, 1141, 'Stufa a Legna',              '9,5 kW',           NULL, NULL),
('Arianna',            'arianna',             true, 1150, 'Stufa a Legna',              '9,5 kW',           NULL, NULL),
('Ester',              'ester',               true, 1160, 'Stufa a Legna',              '7,0 kW',           NULL, NULL),
('Ester Ventilata',    'ester-ventilata',     true, 1161, 'Stufa a Legna',              '7,0 kW',           NULL, NULL),
('Gilda',              'gilda',               true, 1170, 'Stufa a Legna',              '6,0 kW',           NULL, NULL),
('Sandra',             'sandra',              true, 1180, 'Stufa a Legna',              '7,0 kW',           NULL, NULL),
('Regina',             'regina',              true, 1190, 'Stufa a Legna',              '9,5 kW',           NULL, NULL),
('Lino',               'lino',                true, 1200, 'Inserto a Legna',            '14,5 kW',          NULL, NULL),
('Penelope',           'penelope',            true, 1210, 'Stufa a Legna',              '6,6 kW',           NULL, NULL),
('Checco 8-11',        'checco-8-11',         true, 1220, 'Stufa a Legna',              NULL,               NULL, NULL),
('Teresa',             'teresa',              true, 1230, 'Stufa a Legna',              NULL,               NULL, NULL),
('Wanda',              'wanda',               true, 1240, 'Cucina a Legna',             NULL,               NULL, NULL),
('Elvira',             'elvira',              true, 1250, 'Cucina a Legna',             NULL,               NULL, NULL),
('Irma Plus',          'irma-plus',           true, 1260, 'Stufa a Pellet',             '9,5 kW',           NULL, NULL),
('Hydro 24-20',        'hydro-24-20',         true, 1270, 'Caldaia a Pellet',           '25,5 - 20,0 kW',   NULL, NULL),
('Venere 13',          'venere-13',           true, 1280, 'Termostufa a Pellet',        '12,5 kW',          NULL, NULL),
('Frida 13',           'frida-13',            true, 1290, 'Termostufa a Pellet',        '12,5 kW',          NULL, NULL),
('Venere 17,5',        'venere-17-5',         true, 1300, 'Termostufa a Pellet',        '17,5 kW',          NULL, NULL),
('Frida 17,5',         'frida-17-5',          true, 1310, 'Termostufa a Pellet',        '17,5 kW',          NULL, NULL),
('PRO 24-20',          'pro-24-20',           true, 1320, 'Caldaia a Pellet',           '24,5 - 20,1 kW',   NULL, NULL),
('EV 50-34',           'ev-50-34',            true, 1330, 'Caldaia a Pellet',           '45,5 - 34,0 kW',   NULL, NULL),
('Sale',               'sale',                true, 1340, 'Focolare Outdoor a Pellet',  NULL,               NULL, NULL),
('Pepe',               'pepe',                true, 1350, 'Focolare Outdoor a Pellet',  NULL,               'L 30,6 x P 30,6 x H 71,0 cm', '32,8 kg'),
('Olio',               'olio',                true, 1360, 'Focolare Outdoor a Pellet',  NULL,               NULL, NULL)
ON CONFLICT (slug) DO NOTHING;
